(function(){
var oldExtractFile=window.extractFile,oldMeta=window.verifiedPdfMeta,oldClassify=window.classifyItem;
function wait(ms){return new Promise(function(r){setTimeout(r,ms)})}
function clean(s){return typeof cleanText==='function'?cleanText(s):String(s||'').replace(/\s+/g,' ').trim()}
function lines(s){return clean(s).split(/\n+/).map(function(x){return x.trim()}).filter(Boolean)}
function head(s){var a=lines(s).slice(0,70),o=[];for(var i=0;i<a.length;i++){var z=typeof canon==='function'?canon(a[i]):a[i].toLowerCase();if(/^(kính gửi|kinh gui|căn cứ|can cu|thực hiện|thuc hien|theo\b|gửi kèm|gui kem|nơi nhận|noi nhan)/i.test(z))break;o.push(a[i]);if(o.length>=42)break}return o}
function block(text,label){var p=String(text||'').indexOf('--- '+label+' ---');if(p<0)return'';var s=String(text).slice(p+label.length+8),q=s.indexOf('\n--- ');return clean(q>=0?s.slice(0,q):s)}
function page1(text){var m=String(text||'').match(/--- TEXT LAYER TRANG 1 ---\n([\s\S]*?)(?=\n--- |$)/i);return clean(m?m[1]:'')}
function numberFrom(s){var a=head(s);for(var i=0;i<a.length;i++){var m=a[i].match(/(?:Số|Sô|So|S0|S6)\s*[:：]\s*(\d{1,7})\s*[\/\\|]\s*([A-ZĐ0-9][A-ZĐ0-9.\-]{0,40})/i);if(m)return m[1]+'/'+m[2].toUpperCase().replace(/[^A-ZĐ0-9.\-]/g,'')}return''}
function dateFrom(s){var a=head(s);for(var i=0;i<a.length;i++){var m=a[i].match(/(?:ngày|ngay)\s*(\d{1,2})\s*(?:tháng|thang|[\/\-.])\s*(\d{1,2})\s*(?:năm|nam|[\/\-.])\s*(20\d{2})/i);if(m&&validDateParts(+m[1],+m[2],+m[3]))return(+m[1])+'/'+(+m[2])+'/'+m[3]}return''}
function issuerFrom(s){var h=head(s).join(' '),n=typeof norm==='function'?norm(h):h.toLowerCase(),m;if(/uy ban nhan dan/.test(n)){m=h.match(/(?:XÃ|XA|PHƯỜNG|PHUONG|THỊ TRẤN|THI TRAN)\s+([A-Za-zÀ-ỹĐđ0-9]+(?:\s+[A-Za-zÀ-ỹĐđ0-9]+){0,5})/i);if(m)return'UBND '+m[0].replace(/\s+/g,' ').trim();m=h.match(/(?:TỈNH|TINH)\s+([A-Za-zÀ-ỹĐđ]+(?:\s+[A-Za-zÀ-ỹĐđ]+){0,4})/i);if(m)return'UBND tỉnh '+m[1].trim();return'UBND'}return''}
function subjectFrom(s){var a=head(s);try{var x=extractSubject(a);if(x&&x!=='KHONG-XAC-DINH')return clean(x).replace(/^V\/?v\s*/i,'')}catch(e){}for(var i=0;i<a.length;i++){if(/^V\/?v\b/i.test(a[i]))return a[i].replace(/^V\/?v\s*/i,'').trim()}return''}
function typeFrom(s,f){if(/\bV\/?v\b/i.test(head(s).join(' ')))return'Công văn';try{return inferDocType(head(s).join('\n'),'x.pdf')||f||'Tài liệu PDF'}catch(e){return f||'Tài liệu PDF'}}
function iso(d){var m=String(d||'').match(/^(\d{1,2})[\/\-.](\d{1,2})[\/\-.](20\d{2})$/);if(m&&validDateParts(+m[1],+m[2],+m[3]))return m[3]+'-'+String(+m[2]).padStart(2,'0')+'-'+String(+m[1]).padStart(2,'0');m=String(d||'').match(/^(20\d{2})[\/\-.](\d{1,2})[\/\-.](\d{1,2})$/);if(m&&validDateParts(+m[3],+m[2],+m[1]))return m[1]+'-'+String(+m[2]).padStart(2,'0')+'-'+String(+m[3]).padStart(2,'0');return''}
async function quick(file){var pdfjs=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.mjs';var pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),useSystemFonts:true}).promise,o=[];for(var i=1;i<=Math.min(pdf.numPages,120);i++){var p=await pdf.getPage(i),tc=await p.getTextContent(),t=clean(tc.items.map(function(x){return x.str}).join(' '));o.push('--- TEXT LAYER TRANG '+i+' ---\n'+t)}return{pages:pdf.numPages,text:o.join('\n')}}
async function mineru(file){var r=await fetch('/api/mineru?action=create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fileName:file.name,pageRange:''})}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'MinerU create lỗi');try{var u=await fetch(j.fileUrl,{method:'PUT',body:file});if(!u.ok)throw new Error('upload '+u.status)}catch(e){if(file.size>4200000)throw e;var u2=await fetch('/api/mineru?action=upload&url='+encodeURIComponent(j.fileUrl),{method:'POST',headers:{'Content-Type':'application/pdf'},body:file}),j2=await u2.json();if(!u2.ok||!j2.ok)throw new Error(j2.error||'MinerU upload lỗi')}for(var i=0;i<70;i++){await wait(i<5?1200:2200);var s=await fetch('/api/mineru?action=status&taskId='+encodeURIComponent(j.taskId),{cache:'no-store'}),q=await s.json();if(!s.ok||!q.ok)throw new Error(q.error||'MinerU status lỗi');if(q.state==='failed')throw new Error(q.error||'MinerU OCR lỗi');if(q.state==='done'){var m=await fetch('/api/mineru?action=markdown&url='+encodeURIComponent(q.markdownUrl),{cache:'no-store'});if(!m.ok)throw new Error('MinerU markdown lỗi');return await m.text()}if(typeof v4Status==='function')v4Status('OCR scan: MinerU '+(q.state||'đang xử lý')+'…')}throw new Error('MinerU quá thời gian')}
window.extractFile=async function(file){if(ext(file.name)!=='pdf')throw new Error('Chỉ nhận PDF.');var q=null;try{q=await quick(file)}catch(e){}var h=q?page1(q.text):'',ok=h&&numberFrom(h)&&dateFrom(h)&&subjectFrom(h);if(ok)return q.text;if(file.size<=10485760){try{if(typeof v4Status==='function')v4Status('PDF scan: dùng MinerU Flash OCR tiếng Việt, không cần token…');var md=await mineru(file),first=md.split(/\r?\n/).slice(0,65).join('\n');return clean('--- MINERU HEADER ---\n'+first+'\n--- MINERU FULL DOCUMENT ---\n'+md+'\n'+(q?q.text:''))}catch(e){console.warn(e);if(typeof v4Status==='function')v4Status('MinerU lỗi, chuyển OCR cục bộ…',true)}}if(oldExtractFile)return oldExtractFile(file);throw new Error('Không đọc được PDF scan.')};
window.verifiedPdfMeta=function(text,name){var b=oldMeta?oldMeta(text,name):{},mh=block(text,'MINERU HEADER'),nh=page1(text),lh='';try{lh=pdfPageBlock(text,1,'OCR HEADER')||pdfPageBlock(text,1,'OCR FULL')||''}catch(e){}var src=[mh,nh,lh].filter(Boolean),no='',date='',issuer='',subject='',type='';for(var i=0;i<src.length;i++){no=no||numberFrom(src[i]);date=date||dateFrom(src[i]);issuer=issuer||issuerFrom(src[i]);type=type||typeFrom(src[i],b.type);subject=subject||subjectFrom(src[i])}no=no||(b.no&&b.no!=='KHONG-XAC-DINH'?b.no:'');date=date||b.date||'';issuer=issuer||(b.issuer&&b.issuer!=='KHONG-XAC-DINH'?b.issuer:'');subject=subject||(b.subject&&b.subject!=='KHONG-XAC-DINH'?b.subject:'');type=type||b.type||'Tài liệu PDF';var miss=[];if(!/^\d{1,7}\/[A-ZĐ0-9][A-ZĐ0-9.\-]{0,40}$/i.test(no))miss.push('số/ký hiệu');if(!iso(date))miss.push('ngày ban hành');if(!issuer)miss.push('cơ quan');if(!subject||subject.length<7)miss.push('trích yếu');return Object.assign({},b,{no:no||'KHONG-XAC-DINH',date:date,year:(String(date).match(/20\d{2}/)||[])[0]||'KHONG-XAC-DINH',issuer:issuer||'KHONG-XAC-DINH',subject:subject||'KHONG-XAC-DINH',type:type,releaseReady:miss.length===0,missing:miss,source:mh?'MinerU Flash OCR + PDF text layer':'PDF/OCR Header-Lock'})};
var STOP=new Set('VE VIEC CONG TAC CUA THEO VA TRONG NAM TREN DIA BAN CAC DOI VOI TAI THUC HIEN TRIEN KHAI MOT SO NHAM PHUC VU'.split(' '));
function compact(s){var x=String(s||'').replace(/^\s*V\/?v\s*/i,'').replace(/^\s*Về\s+việc\s*/i,'').replace(/Hệ\s*thống\s*quản\s*lý\s*chất\s*lượng/gi,'HTQLCL').replace(/Tiêu\s*chuẩn\s*quốc\s*gia/gi,'TCVN').replace(/ISO\s*9001\s*[:\-]?\s*2015/gi,'ISO9001-2015'),a=safe(x).split('-').filter(Boolean),k=[];for(var i=0;i<a.length;i++){if(STOP.has(a[i]))continue;if(k.indexOf(a[i])<0)k.push(a[i]);if(k.length>=10)break}var z=k.join('-')||'TRICH-YEU';return z.length>48?z.slice(0,48).replace(/-+[^-]*$/,'').replace(/-+$/,''):z}
function issuerToken(s){return safe(String(s||'').replace(/Độc lập[\s\S]*/i,'').replace(/Doc lap[\s\S]*/i,'')).replace(/^UY-BAN-NHAN-DAN-/,'UBND-').replace(/^HOI-DONG-NHAN-DAN-/,'HDND-').slice(0,34)||'CO-QUAN'}
function fileName(vm,type,subject,e){if(!vm||!vm.releaseReady)return'—';var d=iso(vm.date);if(!d)return'—';var fixed=d+'_'+safe(type||vm.type).slice(0,18)+'_'+safe(String(vm.no).replace(/[\/\\|]+/g,'-')).slice(0,32)+'_'+issuerToken(vm.issuer)+'_',ex=String(e||'pdf').replace(/[^a-z0-9]/gi,'').toLowerCase()||'pdf',t=compact(subject||vm.subject),budget=Math.max(22,110-fixed.length-ex.length-1);if(t.length>budget)t=t.slice(0,budget).replace(/-+[^-]*$/,'').replace(/-+$/,'');return fixed+t+'.'+ex}
window.classifyItem=async function(item){var r=await oldClassify(item),vm=window.verifiedPdfMeta(item.text||'',item.name||''),subject=vm.subject&&vm.subject!=='KHONG-XAC-DINH'?vm.subject:(r&&r.profile?r.profile.subject:'');if(r){r.meta=Object.assign({},r.meta||{},vm);r.type=vm.type||r.type;r.suggested=fileName(vm,r.type,subject,ext(item.name));if(!vm.releaseReady)r.status='CHƯA ĐỦ CĂN CỨ ĐẶT TÊN: '+vm.missing.join(', ')}return r};
try{var el=document.querySelector('#aiStatus');if(el)el.textContent='Reader Engine 3.5 · Scan-safe · tên file chuẩn ngắn'}catch(e){}
})();