(() => {
  const V="3.3 Header-Lock", oldExtract=window.extractPdf, oldMeta=window.verifiedPdfMeta, oldScore=window.scoreFolder;
  function H(b){const a=linesOf(b||"").slice(0,48),o=[];for(const r of a){const l=cleanText(r),c=canon(l);if(!l)continue;if(/^(kính gửi|kinh gui|thực hiện|thuc hien|căn cứ|can cu|theo\b|gửi kèm|gui kem|nơi nhận|noi nhan|i[.\s]|1[.\s])/i.test(c))break;o.push(l);if(o.length>=32)break}return cleanText(o.join("\n"))}
  function N(b){const a=linesOf(normalizeOcrAnchors(H(b))).slice(0,34);for(let i=0;i<a.length;i++){if(!/\bSố\s*[:：]/i.test(a[i]))continue;let m=a[i].match(/\bSố\s*[:：]\s*(\d{1,7})\s*[\/\\|]\s*([A-ZĐ0-9][A-ZĐ0-9.\-]{0,40})\b/i);if(m&&validSymbolSuffix(m[2]))return m[1]+"/"+m[2].toUpperCase().replace(/[^A-ZĐ0-9.\-]/g,"");m=a[i].match(/\bSố\s*[:：]\s*(\d{1,7})\s*$/i);if(m&&a[i+1]){const n=a[i+1].match(/^\s*[\/\\|]\s*([A-ZĐ0-9][A-ZĐ0-9.\-]{0,40})\b/i);if(n&&validSymbolSuffix(n[1]))return m[1]+"/"+n[1].toUpperCase()}}return ""}
  function NR(b){const z=normalizeOcrAnchors(b||"");const m=z.match(/(?:\bSố\s*[:：]\s*)?(\d{1,7})\s*[\/\\|]\s*([A-ZĐ0-9][A-ZĐ0-9.\-]{1,40})\b/i);return m&&validSymbolSuffix(m[2])?m[1]+"/"+m[2].toUpperCase().replace(/[^A-ZĐ0-9.\-]/g,""):""}
  function D(b){const a=linesOf(normalizeOcrAnchors(H(b))).slice(0,36);for(let i=0;i<a.length;i++){if(!/\bngày\b/i.test(a[i]))continue;const z=a[i]+" "+(a[i+1]||"");let m=z.match(/\bngày\s*(\d{1,2})\s*(?:tháng|[\/\-.])\s*(\d{1,2})\s*(?:năm|[\/\-.])\s*(20\d{2})\b/i);if(m&&validDateParts(+m[1],+m[2],+m[3]))return (+m[1])+"/"+(+m[2])+"/"+m[3];m=z.match(/\bngày\s*(\d{1,2})[\/\-.](\d{1,2})[\/\-.](20\d{2})\b/i);if(m&&validDateParts(+m[1],+m[2],+m[3]))return (+m[1])+"/"+(+m[2])+"/"+m[3]}return ""}
  function DR(b){const z=normalizeOcrAnchors(b||"");let m=z.match(/\bngày\s*(\d{1,2})\s*(?:tháng|[\/\-.])\s*(\d{1,2})\s*(?:năm|[\/\-.])\s*(20\d{2})\b/i);if(m&&validDateParts(+m[1],+m[2],+m[3]))return (+m[1])+"/"+(+m[2])+"/"+m[3];m=z.match(/\b(\d{1,2})[\/\-.](\d{1,2})[\/\-.](20\d{2})\b/);return m&&validDateParts(+m[1],+m[2],+m[3])?(+m[1])+"/"+(+m[2])+"/"+m[3]:""}
  function I(b){let h=H(b).replace(/CỘNG HÒA[\s\S]*/i,"").replace(/CONG HOA[\s\S]*/i,"").replace(/Độc lập[\s\S]*/i,"").replace(/Doc lap[\s\S]*/i,"").replace(/\bSố\s*[:：][\s\S]*/i,"").trim();let m;if(/uy ban nhan dan/.test(norm(h))){m=h.match(/(?:XÃ|XA|PHƯỜNG|PHUONG|THỊ TRẤN|THI TRAN|ĐẶC KHU|DAC KHU)\s+([A-Za-zÀ-ỹĐđ0-9]+(?:\s+[A-Za-zÀ-ỹĐđ0-9]+){0,5})/i);if(m)return "UBND "+m[0].replace(/\s+/g," ").trim();m=h.match(/(?:TỈNH|TINH)\s+([A-Za-zÀ-ỹĐđ]+(?:\s+[A-Za-zÀ-ỹĐđ]+){0,4})/i);if(m)return "UBND tỉnh "+m[1].trim();return "UBND"}return issuerCandidate(h)}
  function S(b){const h=H(b),s=extractSubject(linesOf(h));if(s)return cleanSubjectExact(s,"Công văn");return extractHeadingTitleRobust(h,inferDocType(h,"x.pdf"))}
  function rowCrop(src,items,rx,fb,left){const hit=(items||[]).find(x=>rx.test(canon(String(x&&x.text||""))));if(!hit)return cropRectCanvas(src,fb[0],fb[1],fb[2],fb[3]);const b=ocrItemBox(hit),cy=(b.y1+b.y2)/2/src.height,bh=Math.max(.028,(b.y2-b.y1)/src.height*2.8),y=Math.max(0,cy-bh/2),hh=Math.min(.105,Math.max(.055,bh));return left?cropRectCanvas(src,.025,y,.50,hh):cropRectCanvas(src,.45,y,.53,hh)}
  async function rowOCR(c,label,kind){const rows=[],big=document.createElement("canvas");big.width=c.width*2;big.height=c.height*2;big.getContext("2d").drawImage(c,0,0,big.width,big.height);try{const p=await paddleOcrCanvas(big,label+" Paddle",{textDetBoxThresh:.12,textRecScoreThresh:.06,textDetLimitSideLen:1800});if(p&&p.text)rows.push({f:"P",t:p.text,c:p.confidence||0})}catch(e){}try{const g=enhanceOcrCanvas(c),u=upscaleBinaryCanvas(g,3),t=await ocrCanvas(u,label+" Tesseract",{tessedit_pageseg_mode:"7",tessedit_char_whitelist:""});if(t&&t.text)rows.push({f:"T",t:t.text,c:t.confidence||0});g.width=g.height=u.width=u.height=1}catch(e){}big.width=big.height=1;const parse=kind==="n"?NR:DR,p=rows.find(x=>x.f==="P"),t=rows.find(x=>x.f==="T"),pv=p&&parse(p.t),tv=t&&parse(t.t),ok=!!(pv&&tv&&canon(pv)===canon(tv));return {v:ok?pv:"",ok:ok,c:ok?Math.min(99,((p.c||0)+(t.c||0))/2):0}}
  window.extractPdf=async function(ab){let text=await oldExtract(ab);try{const pdfjs=await import("https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.mjs");pdfjs.GlobalWorkerOptions.workerSrc="https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.mjs";const pdf=await pdfjs.getDocument({data:new Uint8Array(ab),useSystemFonts:true}).promise,pg=await pdf.getPage(1),page=await renderPdfPage(pg,4),top=cropRectCanvas(page,0,0,1,.31);let items=[],tt="";try{const p=await paddleOcrCanvas(top,"Trang 1 Header-Lock",{textDetBoxThresh:.12,textRecScoreThresh:.06,textDetLimitSideLen:2200});items=p&&p.items||[];tt=p&&p.text||""}catch(e){}const nc=rowCrop(top,items,/(^|\s)(số|so)\b/i,[.025,.31,.50,.22],true),dc=rowCrop(top,items,/(ngày|ngay|bảo lâm|bao lam|lâm đồng|lam dong)/i,[.45,.31,.53,.22],false),nr=await rowOCR(nc,"Số/ký hiệu","n"),dr=await rowOCR(dc,"Ngày ban hành","d"),x=[];if(tt)x.push("--- STRICT HEADER TRANG 1 [CONF 90] ---\n"+tt);if(nr.ok)x.push("--- STRICT NUMBER TRANG 1 [CONF "+nr.c.toFixed(1)+"] ---\nSố: "+nr.v+"\nVERIFIED: YES");if(dr.ok)x.push("--- STRICT DATE TRANG 1 [CONF "+dr.c.toFixed(1)+"] ---\nngày "+dr.v+"\nVERIFIED: YES");if(x.length)text=cleanText(x.join("\n")+"\n"+text);nc.width=nc.height=dc.width=dc.height=top.width=top.height=page.width=page.height=1}catch(e){console.warn("Header-Lock",e)}return text};
  if(!folders.some(f=>f.code==="CCHC.01")){const k=Math.max(0,folders.findIndex(f=>f.code==="TTHC.01")+1);folders.splice(k,0,{code:"CCHC.01",field:"Cải cách hành chính - ISO",work:"Áp dụng, duy trì, cải tiến HTQLCL",name:"HTQLCL theo TCVN ISO 9001:2015",strong:["hệ thống quản lý chất lượng","htqlcl","tcvn iso 9001:2015","iso 9001:2015","duy trì và cải tiến htqlcl"],weak:["cải cách hành chính","thủ tục hành chính","công bố lại","quy trình iso"],exclude:[],semantic:"áp dụng duy trì cải tiến hệ thống quản lý chất lượng HTQLCL theo TCVN ISO 9001:2015 trong cơ quan hành chính nhà nước"})}
  window.scoreFolder=function(folder,profile,name){const r=oldScore(folder,profile,""),p=canon((profile&&profile.subject||"")+" "+(profile&&profile.purpose||""));if(folder.code==="CCHC.01"&&/(htqlcl|he thong quan ly chat luong|tcvn\s*iso\s*9001|iso\s*9001)/i.test(p))r.score+=20;if(folder.code==="VHXH.01"&&/(htqlcl|he thong quan ly chat luong|tcvn\s*iso\s*9001|iso\s*9001)/i.test(p))r.score-=12;return r};
  window.verifiedPdfMeta=function(text,name){const b=oldMeta(text,name),tl=pdfPageBlock(text,1,"TEXT LAYER")||"",sh=pdfPageBlock(text,1,"STRICT HEADER")||"",ph=pdfPageBlock(text,1,"PADDLE HEADER")||"",th=pdfPageBlock(text,1,"TESS HEADER")||"",sn=pdfPageBlock(text,1,"STRICT NUMBER")||"",sd=pdfPageBlock(text,1,"STRICT DATE")||"",src=[{label:"Strict row",family:"StrictRow",text:sn+"\n"+sd,confidence:99,weight:3},{label:"Native header",family:"NativeText",text:H(tl),confidence:textQuality(tl).good?99:62,weight:textQuality(tl).good?2.8:1},{label:"Strict header",family:"PaddleStrict",text:H(sh),confidence:88,weight:2},{label:"Paddle header",family:"PaddleOCR",text:H(ph),confidence:pdfOcrConfidence(text,1,"PADDLE HEADER")||65,weight:1.6},{label:"Tess header",family:"Tesseract",text:H(th),confidence:pdfOcrConfidence(text,1,"TESS HEADER")||55,weight:1.1}].filter(x=>x.text),nv=candidateVote(src,N),dv=candidateVote(src,D),iv=candidateVote(src,I);let no=nv.verified?nv.value:N(sn),date=dv.verified?dv.value:D(sd),issuer=iv.verified?iv.value:(I(tl)||I(sh)||""),subject=S(tl)||S(sh)||S(ph)||b.subject,type=inferDocType(H(tl||sh||ph),name),by=docTypeFromNumber(no);if(by)type=by;issuer=(issuer||"").replace(/\s+(Độc lập|Doc lap)[\s\S]*/i,"").trim();const nok=/^\d{1,7}\/[A-ZĐ0-9][A-ZĐ0-9.\-]{0,40}$/i.test(no),dok=!!dateCompact(date),iok=!!issuer&&issuer!=="KHONG-XAC-DINH",sok=!!subject&&subject!=="KHONG-XAC-DINH"&&subject.length>=8,signed=b.digitalSignature||(b.redSeal&&b.signatureBlock),ready=nok&&dok&&iok&&sok&&signed,miss=[];if(!nok)miss.push("chưa xác minh số/ký hiệu ở dòng Số:");if(!dok)miss.push("chưa xác minh ngày ban hành ở vùng đầu trang");if(!iok)miss.push("chưa xác minh cơ quan ban hành ở cột trái");if(!sok)miss.push("chưa xác minh chính xác trích yếu");if(!signed)miss.push("chưa xác minh trạng thái đã ký/phát hành");return Object.assign({},b,{no:no||"KHONG-XAC-DINH",date:date,year:(date.match(/20\d{2}/)||[])[0]||"KHONG-XAC-DINH",issuer:issuer||"KHONG-XAC-DINH",subject:subject||"KHONG-XAC-DINH",type:type,releaseReady:ready,missing:miss,source:"BL2 Reader Engine "+V+" · chỉ lấy metadata trước Kính gửi · khóa văn bản viện dẫn"})};
  window.extractMeta=function(text,name){const m=window.verifiedPdfMeta(text,name);return {date:m.date,no:m.no,year:m.year}};
  const st=document.querySelector("#aiStatus");if(st)st.textContent="Reader Engine 3.3 · Header-Lock + OCR scan chữ viết tay đen/màu";
})();